config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  match "setposition" => 'home#setposition', via: :post
  root 'home#index'

end

app/models/arduino.rb
class Arduino
  attr_accessor :person, :place, :pin #making specifics available outside of class

  def initialize(person, place, pin) #initializer to create new arduino
    @person = person
    @place = place
    @pin = pin
    @angle = 0

## Case change based on where you are going
    case place
    when "work"
      @angle = 100
    when "home"
      @angle = 225
    else
      @angle = 0
    end

## "COM#" to be set form Windows, leave blank for '/dev/ttyACM0' if on linux
    arduino = ArduinoFirmata.connect "COM6"
    1.times do
      arduino.digital_write 13, true
      arduino.servo_write @pin, @angle
      sleep 1
      arduino.digital_write 13, false
      arduino.close
    end

  end # end of initialize
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/arduino_controller.rb
class ArduinoController < ApplicationController
  def setposition
    @arduino = Arduino.new("Me", "work", 11)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def setposition
    begin
      if params[:person] && params[:place] && params[:pin]
        person = params[:person]
        place = params[:place]
        pin = params[:pin].to_i
        @arduino = Arduino.new(person, place, pin)
      else
        flash[:notice] = "Oops!  It didn't work!"
      end
    rescue
      flash[:notice] = "The arduino needs reset... or reconnected..."
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/arduino_helper.rb
module ArduinoHelper
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Where AM I!?</h1>
<p>Tell us where You are or are off to!</p>
<div class="btn-group">
  <%= link_to "Set Work", setposition_path(person: "me", place: "work", pin: 11),
      method: :post, class: "btn btn-default" %>
  <%= link_to "Set Home", setposition_path(person: "me", place: "home", pin: 11),
      method: :post, class: "btn btn-success" %>
  <%= link_to "Set Another place", setposition_path(person: "me", place: "somewhere", pin: 11),
      method: :post, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebduinoController</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
  </head>
  <body>

    <div class="container">
      <% if notice %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %> <!-- end of notices -->
      <%= yield %>
    </div>
  </body>
</html>